bool hitSphere(vec3 sphereCenter, float radius, ray r, Interval ray_t, inout hit_record rec);
vec3 ray_color(in ray r);
ray generateCameraRay(vec4 frag);
Interval interval_tight(Interval a, Interval b);
bool interval_contains(Interval i, float x);
bool interval_surrounds(Interval i, float x);
float clamp(Interval i, float x);
bool hitScene(ray r, inout hit_record rec);
bool scatterLambertian(in ray r,in hit_record rec, inout vec3 attenuation, inout ray scattered);
bool scatterMetal(in ray r, in hit_record rec, inout vec3 attenuation, inout ray scattered);